steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # Replace with your zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=your-cluster-name' # Replace with your cluster name

images: ['gcr.io/$PROJECT_ID/my-app:$BUILD_ID']
